using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using DL_PUBLIC;

/// <summary>
/// Summary description for IsAutoGenerated
/// </summary>
public class IsAutoGenerated
{
	public IsAutoGenerated()
	{
		//
		// TODO: Add constructor logic here
		//
	}

    public static DataTable IsAccoutAuto(int Event, int id, string accId, string Code, DateTime? Date)
    {
        SqlCommand cmd = new SqlCommand();
        DataTable dt = new DataTable();
        try
        {

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "USP_SELECT_IS_AUTO_GENERATE";
            cmd.Parameters.AddWithValue("@EVENT", Event);
            cmd.Parameters.AddWithValue("@ID", id);
            cmd.Parameters.AddWithValue("@accId", accId);
            cmd.Parameters.AddWithValue("@CODE", Code);
            cmd.Parameters.AddWithValue("@Date", Date);
            cmd.Connection = DL_CCommon.ConnectionForCommonDb();
            IDataReader dr = cmd.ExecuteReader();
            dt.Load(dr);
            cmd.Dispose();
            return dt;
        }
        catch (Exception ex)
        {
            throw new ArgumentException(ex.Message);
        }
        finally
        {
            DL_CCommon.ConnectionForCommonDb().Close();
        }
    }
}