<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="WorkingAreaSetup.aspx.cs" Inherits="Benetton.Settings.WorkingAreaSetup" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:UpdatePanel ID="updForm" runat="server">
        <ContentTemplate>
            <asp:Panel ID="pnlMsgBox" runat="server">
            </asp:Panel>
            <asp:UpdateProgress ID="updProgress" runat="server" AssociatedUpdatePanelID="updForm">
                <ProgressTemplate>
                    <img src="../Images/progress.gif" alt="Loading..." />
                </ProgressTemplate>
            </asp:UpdateProgress>
        </ContentTemplate>
    </asp:UpdatePanel>
    <div class="form_inner">
        <h2>
            Working Area Settings
        </h2>
        <ul>
           <li>
                        <label>
                            Zone *
                        </label>
                        <asp:DropDownList ID="ddlPermanentZone" runat="server" Width="135px">
                        </asp:DropDownList>
                    </li>
            <li>
                <label>
                    District *
                </label>
                <asp:TextBox ID="txtDistrict" onkeyup="CheckFirstChar(event.keyCode, this);" onkeydown="return CheckFirstChar(event.keyCode, this);"
                    runat="server"></asp:TextBox>
            </li>
            <li>
                <label>
                    VDC
                </label>
                <asp:TextBox ID="txtVDC" onkeyup="CheckFirstChar(event.keyCode, this);" onkeydown="return CheckFirstChar(event.keyCode, this);"
                    runat="server"></asp:TextBox>
            </li>
            <li>
                <label>
                    MPC
                </label>
                <asp:TextBox ID="txtMPC" onkeyup="CheckFirstChar(event.keyCode, this);" onkeydown="return CheckFirstChar(event.keyCode, this);"
                    runat="server"></asp:TextBox>
            </li>
            <li>
                <label>
                    &nbsp
                </label>
                <asp:Button ID="btnSubmit" runat="server" OnClick="btnSubmit_Click" Text="Submit" ValidationGroup="v"
                    CssClass="btn" OnClientClick="return confirm('Confirm to save?')" />
            </li>
        </ul>
        <div class="clear">
        </div>
        <asp:Panel ID="pnlWArea" runat="server">
            <asp:GridView ID="gvWArea" runat="server" AutoGenerateColumns="False" DataSourceID="dsWArea"
                CellPadding="4" Width="100%" CssClass="table1" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" DataKeyNames="Id" AllowPaging="true" PageSize="40"
                OnPageIndexChanging="gvWArea_PageIndexChanging">
                <Columns>
                     <asp:TemplateField HeaderText="Zone" SortExpression="Zone">
                        <ItemTemplate>
                            <asp:Label ID="lblZone" runat="server" Text='<%# Bind("Zone") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="District" SortExpression="District">
                        <ItemTemplate>
                            <asp:Label ID="lblDistrict" runat="server" Text='<%# Bind("District") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDistrict" runat="server" Text='<%# Bind("District") %>'></asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="MPC" SortExpression="MPC">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtMPC" runat="server" Text='<%# Bind("MPC") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblMPC" runat="server" Text='<%# Bind("MPC") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="VDC" SortExpression="VDC">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtVDC" runat="server" Text='<%# Bind("VDC") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblVDC" runat="server" Text='<%# Bind("VDC") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <PagerStyle CssClass="pgr" HorizontalAlign="Right" />
                <AlternatingRowStyle CssClass="alt" />
            </asp:GridView>
            <asp:SqlDataSource ID="dsWArea" runat="server" ConnectionString="<%$ ConnectionStrings:CSCommonDB %>"
                SelectCommand="SELECT * FROM [tbl_WorkingArea] " UpdateCommand="Update tbl_WorkingArea set Zone=@Zone,District=@District,MPC=@MPC,VDC=@VDC where Id=@Id"
                DeleteCommand="Delete from tbl_WorkingArea where Id=@Id"></asp:SqlDataSource>
        </asp:Panel>
    </div>
</asp:Content>
