using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using DataLogic;

/// <summary>
/// Summary description for IsAutoGenerate
/// </summary>
public class IsAutoGenerate
{
	public IsAutoGenerate()
	{
		//
		// TODO: Add constructor logic here
		//

	}

    #region private fields...
    private int _EVENT = 0; public int EVENT { get { return _EVENT; } set { _EVENT = value; } }
    private int _Acc_ID = 0; public int Acc_ID { get { return _Acc_ID; } set { _Acc_ID = value; } }
    private string _Acc_Head = string.Empty; public string Acc_Head { get { return _Acc_Head; } set { _Acc_Head = value; } }
    private int _Acc_ParentID = 0; public int Acc_ParentID { get { return _Acc_ParentID; } set { _Acc_ParentID = value; } }     
    private DateTime? _Dates = Convert.ToDateTime("01/01/1973"); public DateTime? Dates { get { return _Dates; } set { _Dates = value; } }
    private string _Remarks = string.Empty; public string Remarks { get { return _Remarks; } set { _Remarks = value; } }
    private bool _IsAuto = false; public bool IsAuto { get { return _IsAuto; } set { _IsAuto = value; } }
    private int _CreatedBy = 0; public int CreatedBy { get { return _CreatedBy; } set { _CreatedBy = value; } }
    private DateTime? _CreatedDate = Convert.ToDateTime("01/01/1973"); public DateTime? CreatedDate { get { return _CreatedDate; } set { _CreatedDate = value; } }
    private int _ModifiedBy = 0; public int ModifiedBy { get { return _ModifiedBy; } set { _ModifiedBy = value; } }
    private DateTime? _ModifiedDate = Convert.ToDateTime("01/01/1973"); public DateTime? ModifiedDate { get { return _ModifiedDate; } set { _ModifiedDate = value; } }
    private int _Branch_id = 0; public int Branch_id { get { return _Branch_id; } set { _Branch_id = value; } }
    private bool _Acc_Primary = false; public bool Acc_Primary { get { return _Acc_Primary; } set { _Acc_Primary = value; } }
    private bool _IsLoanAutoGenerate = false; public bool IsLoanAutoGenerate { get { return _IsLoanAutoGenerate; } set { _IsLoanAutoGenerate = value; } }     
    private string _VoucherNo = string.Empty; public string VoucherNo { get { return _VoucherNo; } set { _VoucherNo = value; } }
    private string _LoanNo = string.Empty; public string LoanNo { get { return _LoanNo; } set { _LoanNo = value; } }
    private string _MemberNo = string.Empty; public string MemberNo { get { return _MemberNo; } set { _MemberNo = value; } }
    private int _flag_bank_cash = 0; public int flag_bank_cash { get { return _flag_bank_cash; } set { _flag_bank_cash = value; } }
    private bool _isABBS = false; public bool isABBS { get { return _isABBS; } set { _isABBS = value; } }
    private string _PROCEDURE = string.Empty; public string PROCEDURE { get { return _PROCEDURE; } set { _PROCEDURE = value; } }
    private int _ID = 0; public int ID { get { return _ID; } set { _ID = value; } }
    private string _CODE = string.Empty; public string CODE { get { return _CODE; } set { _CODE = value; } }
    #endregion

    public static bool IsAccoutAuto(int Event,int id, string accId,string Code,DateTime? Date)
    {
        bool IsAutoGene = false;
        DataTable dt =IsAutoGenerated.IsAccoutAuto(Event,id,accId,Code,Date);
        if (dt.Rows.Count > 0)
        {
            IsAutoGene = Convert.ToBoolean(dt.Rows[0]["IsAutoGenerate"]);
        }
        return IsAutoGene;
    }


}